### PR TITLE
TracingInterceptor tests fails in Micronaut Reactor

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by sdelamo** [comment]
@dstepanov TraceInterceptorSpec.test trace mono test fails. Can you investigate?

**Comment by n0tl3ss** [comment]
Hi @sdelamo, changing test code to makes test pass:

```
        @NewSpan("trace-mono")
        Publisher<String> mono(@SpanTag("more.stuff") String name) {
            return ReactivePropagation.propagate(
                    PropagatedContext.get(),
                    Mono.fromCallable({
                        spanCustomizer.tag("foo", "bar")
                        return name
                    }).subscribeOn(Schedulers.boundedElastic())
            )
        }
```

I guess the issue is with `subscribeOn` part because it happens on another thread.

**Comment by dstepanov** [comment]
I will check

**Comment by sdelamo** [comment]
@dstepanov can you check this?

**Comment by dstepanov** [comment]
This is not supported by default, but the propagation using Micrometer should work

**Pull request merged**
