### PR TITLE
build: update to Reactor 3.5.0

### PR DESCRIPTION
**Pull request by sdelamo**
- Micronaut Framework 3.7.4  
- Micronaut Test3.7.1

### CODE REVIEW

**Comment by sdelamo** [comment]
@timyates can you check the failure in this PR?

**Comment by timyates** [comment]
The remaining tests are failing due to https://github.com/micronaut-projects/micronaut-core/pull/8155 which was fixed on 4.0.x, but needs backporting

**Comment by timyates** [comment]
This is the fix in core https://github.com/micronaut-projects/micronaut-core/pull/8434

**Comment by timyates** [comment]
@sdelamo, I can't remember what we decided with this, it fails for 3.7.x should we bump it to the 3.9.0 project?

**Pull request merged**
